login:
    path: /connexion
    defaults:
        _controller: InstagramBundle:Default:connexion

login_check:
    path: /login_check

logout:
    path: /deconnexion

instagram:
    resource: "@InstagramBundle/Resources/config/routing.yml"
    prefix:   /

rhodier_platform:
    resource: "@RhodierPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform