<?php

namespace InstagramBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
		public function getCommenairesWithAuthorsBy($id_publication)
		{
				$qb = $this->createQueryBuilder("c");
			
				$qb
					->innerJoin("c.publication", "p")
					->where("p.id = :id_publication")
					->setParameter("id_publication", $id_publication)
					->innerJoin("p.user", "u")
				;

				return $qb
					->getQuery()
					->getResult()
				;
		}
}
