<?php

namespace InstagramBundle\Repository;

/**
 * JaimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JaimeRepository extends \Doctrine\ORM\EntityRepository
{
		public function nbrJaimes($publication_id)
		{
				$qb = $this->createQueryBuilder('j');
				$qb
						->where($qb->expr()->in("j.publication", $publication_id))
						->select($qb->expr()->count("j"))
				;

				return $qb->getQuery()->getSingleScalarResult();
		}
}
