<?php

namespace InstagramBundle\Repository;
use InstagramBundle\Entity\User;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends \Doctrine\ORM\EntityRepository
{
	
		public function nbrPublications($user_id)
		{
				$qb = $this->createQueryBuilder('p');
				$qb
						->innerJoin("p.user", "u")
						->select($qb->expr()->count("u"))
						->where("u.id = :user_id")
						->setParameter("user_id", $user_id)
				;

				return $qb->getQuery()->getSingleScalarResult();
		}
}